language: node_js
node_js:
- '4.6'
before_install:
- npm install -g npm
before_script:
- npm install grunt-cli -g
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: kH5Hhg/fxY2zW7IqBoq2yz2a2aHf/wPJmGTdnB0HCsb4tYpA3aZd7d0gvGjQeAVQItpM+uD/rgBG+Y6gtMkcIdClYpyMQOrZOSg+zWfkRm1kexXOPCU8wCZCGXZsBY2zcuE7wxpjED8fxyWDOhS1sa6Gld8PvWG/D4gnN0vKXUK5H9d9F435sXz4v7LuJ8CEK2NHlj/PxmQFAV9obvQVCNwbijfK4Asoxqv9z8c9eL9cDyw/x/fYmD2XiXBBmOuXaPrpqsEWkXIscvh1cdimosyjBWkH38v372EUOh26b5qauapjbBz8j4E9aHRINMIHP5xizzOrBCxAtr59jxsmq/3TP3c+W7SBNfMirtpw6fRxUtikPHM12oOycJ0BpBzN4RfLfS2bUYaMhqhoyL8TNVRrIAvoMWWkhjJUO5s9AEeOtDG072OqoVD9sPbQuOxbB+Fx1iRVBPHWkakeJOxMJnwSx2IxkfkSMQ4C++81ktTKHs23q68el7V0TUve1A+uf8R23N03y88IieBZBchhQZsUDtNa3vC13vH0U+TxPWE+JKF6BnQYQRNf/LW+RjKOvasKevgYYPZZ4cwhbCVHPMLXRctPXkPtD+P3nee3T37KY71Te5+XQ1C/eD4hV4rydUepXz1Zx785Y9ugwebqE5SmicxzpMVHKBBCh6h+bI8=
  on:
    tags: true
    repo: noflo/noflo-ipfs
